In [ ]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y" -O RSData.zip && rm -rf /tmp/cookies.txt
#https://drive.google.com/file/d/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y/view?usp=sharing
!unzip RSData.zip

--2023-10-24 08:23:09--  https://docs.google.com/uc?export=download&confirm=t&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y
Resolving docs.google.com (docs.google.com)... 74.125.26.102, 74.125.26.113, 74.125.26.139, ...
Connecting to docs.google.com (docs.google.com)|74.125.26.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-04-44-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c9ls85k3k7k08strqilpomrdeiabnc2c/1698135750000/07988131849474548919/*/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y?e=download&uuid=0e50174c-c545-4c4e-9977-ed6a25a3de48 [following]
--2023-10-24 08:23:09--  https://doc-04-44-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c9ls85k3k7k08strqilpomrdeiabnc2c/1698135750000/07988131849474548919/*/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y?e=download&uuid=0e50174c-c545-4c4e-9977-ed6a25a3de48
Resolving doc-04-44-docs.googleusercontent.com (doc-04-44-docs.googleusercontent.com)... 172.217.193.132, 260

##User-User

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
user_friends = pd.read_csv('/content/hetrec2011-lastfm-2k/user_friends.csv')
user_friends

userID  friendID
0           2       275
1           2       428
2           2       515
3           2       761
4           2       831
...       ...       ...
25429    2099      1801
25430    2099      2006
25431    2099      2016
25432    2100       586
25433    2100       607

[25434 rows x 2 columns]

In [ ]:
# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_friends.pivot_table(index=['userID'], columns='friendID', aggfunc='size', fill_value=0)

# Reindex the pivot table to have index from 0 to 2100
# user_friends_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 2101), fill_value=0, axis=1)
user_friends_df = pivot_table

# Reset column names to be 'userID' and 'friendID'
user_friends_df.columns.name = 'friendID'
user_friends_df.index.name = 'userID'

print(user_friends_df)

matrix =user_friends_df.to_numpy()
matrix

friendID  2     3     4     5     6     7     8     9     10    11    ...  \
userID                                                                ...   
2            0     0     0     0     0     0     0     0     0     0  ...   
3            0     0     0     0     0     0     0     0     0     0  ...   
4            0     0     0     0     0     0     0     0     0     0  ...   
5            0     0     0     0     0     0     0     0     0     0  ...   
6            0     0     0     0     0     0     0     0     0     0  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
2095         0     0     0     0     0     0     0     0     0     0  ...   
2096         0     0     0     0     0     0     0     0     0     0  ...   
2097         0     0     0     0     0     0     0     0     0     0  ...   
2099         0     0     0     0     0     0     0     0     0     0  ...   
2100         0     0     0     0     0     0     0     0     0     0  ...   

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
useruser_dict = {i+1: index for i, index in enumerate(user_friends_df.index)}

In [ ]:
useruser_dict

{1: 2,
 2: 3,
 3: 4,
 4: 5,
 5: 6,
 6: 7,
 7: 8,
 8: 9,
 9: 10,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 17,
 17: 18,
 18: 20,
 19: 21,
 20: 22,
 21: 23,
 22: 24,
 23: 25,
 24: 26,
 25: 27,
 26: 28,
 27: 29,
 28: 30,
 29: 31,
 30: 32,
 31: 33,
 32: 34,
 33: 35,
 34: 36,
 35: 37,
 36: 38,
 37: 39,
 38: 40,
 39: 41,
 40: 42,
 41: 43,
 42: 44,
 43: 45,
 44: 46,
 45: 47,
 46: 48,
 47: 49,
 48: 50,
 49: 51,
 50: 52,
 51: 53,
 52: 54,
 53: 55,
 54: 56,
 55: 57,
 56: 58,
 57: 59,
 58: 60,
 59: 61,
 60: 62,
 61: 63,
 62: 64,
 63: 65,
 64: 66,
 65: 68,
 66: 69,
 67: 70,
 68: 71,
 69: 72,
 70: 73,
 71: 74,
 72: 75,
 73: 76,
 74: 77,
 75: 78,
 76: 79,
 77: 80,
 78: 81,
 79: 82,
 80: 83,
 81: 84,
 82: 85,
 83: 86,
 84: 87,
 85: 88,
 86: 89,
 87: 90,
 88: 91,
 89: 92,
 90: 94,
 91: 95,
 92: 96,
 93: 97,
 94: 98,
 95: 99,
 96: 100,
 97: 101,
 98: 102,
 99: 103,
 100: 104,
 101: 105,
 102: 106,
 103: 107,
 104: 108,
 105: 109,
 106: 110,
 107: 111,
 108: 112,
 109: 113,
 110: 114,
 

In [ ]:
matrix.shape

(1892, 1892)

In [ ]:
df = pd.DataFrame(matrix)
df

0     1     2     3     4     5     6     7     8     9     ...  1882  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1887     0     0     0     0     0     0     0     0     0     0  ...     0   
1888     0     0     0     0     0     0     0     0     0     0  ...     0   
1889     0     0     0     0     0     0     0     0     0     0  ...     0   
1890     0     0     0     0     0     0     0     0     0     0  ...     0   
1891     0     0     0     0     0     0     0     0     0     0  ...     0   

      1883  1884  1885  1886  1887  1888  1889  1890  1891  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1887     0     0     0     0     0     0     0     0     0  
1888     0     0     0     0     0     0     0     0     0  
1889     0     0     0     0     0     0     0     0     0  
1890     0     0     0     0     0     0     0     0     0  
1891     0     0     0     0     0     0     0     0     0  

[1892 rows x 1892 columns]

In [ ]:
df.to_csv('user_user.csv', index=False)

##User-Tag

In [ ]:
user_tagged = pd.read_csv("/content/hetrec2011-lastfm-2k/user_taggedartists.csv")
user_tagged

userID  artistID  tagID  day  month  year
0            2        52     13    1      4  2009
1            2        52     15    1      4  2009
2            2        52     18    1      4  2009
3            2        52     21    1      4  2009
4            2        52     41    1      4  2009
...        ...       ...    ...  ...    ...   ...
186474    2100     16437      4    1      7  2010
186475    2100     16437    292    1      5  2010
186476    2100     16437   2087    1      7  2010
186477    2100     16437   2801    1      5  2010
186478    2100     16437   3335    1      7  2010

[186479 rows x 6 columns]

In [ ]:
max_userID = user_tagged['artistID'].max(axis = 0)
max_userID

18744

In [ ]:
# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_tagged.pivot_table(index=['userID'], columns='tagID', aggfunc = 'size').fillna(0)

# Reindex the pivot table to have index from 0 to 2100
# user_tag_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 12649), fill_value=0, axis=1)
user_tag_df = pivot_table
# Reset column names to be 'userID' and 'friendID'
user_tag_df.columns.name = 'tagID'
user_tag_df.index.name = 'userID'

print(user_tag_df)

user_tag_matrix =user_tag_df.to_numpy()
user_tag_matrix

tagID   1      2      3      4      5      6      7      8      9      10     \
userID                                                                         
2         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4         1.0    0.0    0.0    0.0    0.0    1.0    1.0    0.0    0.0    0.0   
5         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
6         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2095      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2096      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2097      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2099      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2100      0.0    0.0    0.0    3.0    0.

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
np.unique(user_tag_df)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 84., 85., 86., 87., 88., 90., 92., 93.,
       94., 95., 96.])

In [ ]:
user_tag_matrix = np.where(user_tag_matrix>1,1,0)

In [ ]:
df = pd.DataFrame(user_tag_matrix)
df

0     1     2     3     4     5     6     7     8     9     ...  9739  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1887     0     0     0     0     0     0     0     0     0     0  ...     1   
1888     0     0     0     0     0     0     0     0     0     0  ...     0   
1889     0     0     0     0     0     0     0     0     0     0  ...     0   
1890     0     0     0     0     0     0     0     0     0     0  ...     0   
1891     0     0     0     1     0     0     0     0     0     0  ...     0   

      9740  9741  9742  9743  9744  9745  9746  9747  9748  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1887     1     1     1     0     0     0     0     0     0  
1888     0     0     0     1     1     1     1     1     1  
1889     0     0     0     0     0     0     0     0     0  
1890     0     0     0     0     0     0     0     0     0  
1891     0     0     0     0     0     0     0     0     0  

[1892 rows x 9749 columns]

In [ ]:
df.to_csv('user_tag.csv', index=False)

##User-Item

In [ ]:
user_item = pd.read_csv("/content/hetrec2011-lastfm-2k/user_taggedartists.csv")
user_item

userID  artistID  tagID  day  month  year
0            2        52     13    1      4  2009
1            2        52     15    1      4  2009
2            2        52     18    1      4  2009
3            2        52     21    1      4  2009
4            2        52     41    1      4  2009
...        ...       ...    ...  ...    ...   ...
186474    2100     16437      4    1      7  2010
186475    2100     16437    292    1      5  2010
186476    2100     16437   2087    1      7  2010
186477    2100     16437   2801    1      5  2010
186478    2100     16437   3335    1      7  2010

[186479 rows x 6 columns]

In [ ]:
max_userID = user_tagged['tagID'].max(axis = 0)
max_userID

12647

In [ ]:

# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_item.pivot_table(index=['userID'], columns='artistID', aggfunc = 'size').fillna(0)

# Reindex the pivot table to have index from 0 to 2100
# user_item_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 18746), fill_value=0, axis=1)
user_item_df = pivot_table
# Reset column names to be 'userID' and 'friendID'
user_item_df.columns.name = 'artistID'
user_item_df.index.name = 'userID'

print(user_item_df)

user_item_matrix =user_item_df.to_numpy()
user_item_matrix

artistID  1      2      3      4      5      6      7      8      9      \
userID                                                                    
2           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
6           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
2095        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2096        0.0    0.0    0.0    0.0    0.0    0.0    2.0    0.0    0.0   
2097        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2099        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2100        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

artistID  10     ...  18

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
user_item_df[2096].loc[user_item_df[2096]==1]

Series([], Name: 2096, dtype: float64)

In [ ]:
np.unique(user_item_df)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
user_item_matrix = np.where(user_item_matrix>1,1,0)

In [ ]:
np.unique(user_item_matrix)

array([0, 1])

In [ ]:
df = pd.DataFrame(user_item_matrix)
df

0      1      2      3      4      5      6      7      8      9      \
0         0      0      0      0      0      0      0      0      0      0   
1         0      0      0      0      0      0      0      0      0      0   
2         0      0      0      0      0      0      0      0      0      0   
3         0      0      0      0      0      0      0      0      0      0   
4         0      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1887      0      0      0      0      0      0      0      0      0      0   
1888      0      0      0      0      0      0      1      0      0      0   
1889      0      0      0      0      0      0      0      0      0      0   
1890      0      0      0      0      0      0      0      0      0      0   
1891      0      0      0      0      0      0      0      0      0      0   

      ...  12513  12514  12515  12516  12517  12518  12519  12520  12521  \
0     ...      0      0      0      0      0      0      0      0      0   
1     ...      0      0      0      0      0      0      0      0      0   
2     ...      0      0      0      0      0      0      0      0      0   
3     ...      0      0      0      0      0      0      0      0      0   
4     ...      0      0      0      0      0      0      0      0      0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1887  ...      0      0      0      0      0      0      0      0      0   
1888  ...      0      0      0      0      0      0      0      0      0   
1889  ...      0      0      0      0      0      0      0      0      0   
1890  ...      1      0      0      0      0      0      0      0      0   
1891  ...      0      0      0      0      0      0      0      0      0   

      12522  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
1887      0  
1888      0  
1889      0  
1890      0  
1891      0  

[1892 rows x 12523 columns]

In [ ]:
df.to_csv('user_item.csv', index=False)

In [ ]:
!jupyter nbconvert --to html --output I040,I057_Input_RS_Project.html I040,_I057_Input_RS_Project.ipynb

[NbConvertApp] Converting notebook I040,_I057_Input_RS_Project.ipynb to html
[NbConvertApp] Writing 690721 bytes to I040,I057_Input_RS_Project.html
